name: Build Images and Handle Uffizzi Previews.

on:
  push:
    branches:
      - main
      - master
      - staging
      - qa
  pull_request:
    types: [opened,reopened,synchronize,closed]

jobs:
  build-backend:
    name: Build and Push `backend`
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.action != 'closed' }}
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository_owner }}/foodadvisor-backend
      - name: Build and Push Image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ./api

  render-compose-file:
    name: Render Docker Compose File
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.action != 'closed' }}
    needs: 
      - build-backend
    outputs:
      compose-file-cache-key: ${{ steps.hash.outputs.hash }}
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Render Compose File
        run: |
          BACKEND_IMAGE=$(echo ${{ needs.build-backend.outputs.tags }})
          export BACKEND_IMAGE
          # Render simple template from environment variables.
          envsubst < docker-compose.template.yaml > docker-compose.rendered.yaml
          cat docker-compose.rendered.yaml
      - name: Hash Rendered Compose File
        id: hash
        run: echo "::set-output name=hash::$(md5sum docker-compose.rendered.yaml | awk '{ print $1 }')"
      - name: Cache Rendered Compose File
        uses: actions/cache@v3
        with:
          path: docker-compose.rendered.yaml
          key: ${{ steps.hash.outputs.hash }}

  deploy-uffizzi-preview:
    name: Use Remote Workflow to Preview on Uffizzi
    needs: render-compose-file
    uses: UffizziCloud/preview-action/.github/workflows/reusable.yaml@labels
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
    with:
      compose-file-cache-key: ${{ needs.render-compose-file.outputs.compose-file-cache-key }}
      compose-file-cache-path: docker-compose.rendered.yaml
      username: adam@idyl.tech
      server: https://app.uffizzi.com
      project: my-application
    secrets:
      password: ${{ secrets.UFFIZZI_PASSWORD }}
      url-username: admin
      url-password: ${{ secrets.URL_PASSWORD }}
      personal-access-token: ${{ secrets.GHCR_ACCESS_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
      id-token: write

  delete-uffizzi-preview:
    name: Use Remote Workflow to Delete an Existing Preview
    uses: UffizziCloud/preview-action/.github/workflows/reusable.yaml@labels
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
    with:
      compose-file-cache-key: ''
      compose-file-cache-path: docker-compose.rendered.yaml
      username: adam@idyl.tech
      server: https://app.uffizzi.com
      project: my-application
    secrets:
      password: ${{ secrets.UFFIZZI_PASSWORD }}
    permissions:
      contents: read
      pull-requests: write
      id-token: write

  deploy-vercel-preview:
    name: Deploy Frontend to Vercel
    needs: deploy-uffizzi-preview
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - env:
          VERCEL_ORG_ID: team_MqEjt3eiv4r2Qu8ya2Q3Dhih
          VERCEL_PROJECT_ID: prj_uU20hVCNAd425Y1bG42AlpPcXgah
        id: vercel-deploy
        run: |
          export NEXT_PUBLIC_API_URL=${{ needs.deploy-uffizzi-preview.outputs.url }}
          echo $NEXT_PUBLIC_API_URL
          yarn install --frozen-lockfile
          npm install --global vercel@latest

          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          export OUTPUT=$(vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --build-env NEXT_PUBLIC_API_URL="$NEXT_PUBLIC_API_URL")

          echo "OUTPUT=$OUTPUT"
          echo "::set-output name=VERCEL_URL::$OUTPUT"
      # If PR event, look for an existing Preview Deployment.
      - name: Find comment for deployment URL
        uses: peter-evans/find-comment@v2
        if: ${{ github.event_name == 'pull_request' }}
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Vercel URL:'
          direction: last
      - name: Create comment for Vercel deployment
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ steps.find-comment.outputs.comment-id == '' && github.event.action != 'closed' }}
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Frontend Preview deployed at Vercel URL:
            ${{ steps.vercel-deploy.outputs.VERCEL_URL }}
          edit-mode: replace
          reactions: rocket
      - name: Update comment for Vercel deployment
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ steps.find-comment.outputs.comment-id != '' && github.event.action != 'closed' }}
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Frontend Preview redeployed at Vercel URL:
            ${{ steps.vercel-deploy.outputs.VERCEL_URL }}
          edit-mode: replace
          reactions: '+1'
